services:
  # Web Service for the main application (Free tier compatible)
  - type: web
    name: alex-voice-agent
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python web_server.py"
    plan: free
    envVars:
      - key: LIVEKIT_API_KEY
        value: APITMKfqYVjk79h
      - key: LIVEKIT_API_SECRET
        value: gCkm5chxksS9KKIUrWVDhf7TDVRVeqleZHf49SFPLBMA
      - key: LIVEKIT_URL
        value: wss://sr-fa31r2za.livekit.cloud
    healthCheckPath: /health

  # Note: Background workers require paid plans on Render
  # For free deployment, keep the agent running on Replit or use alternatives below