services:
  # Web Service for the main application
  - type: web
    name: alex-voice-agent
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python web_server.py"
    plan: free
    envVars:
      - key: LIVEKIT_API_KEY
        value: APITMKfqYVjk79h
      - key: LIVEKIT_API_SECRET
        value: gCkm5chxksS9KKIUrWVDhf7TDVRVeqleZHf49SFPLBMA
      - key: LIVEKIT_URL
        value: wss://sr-fa31r2za.livekit.cloud
      - key: PORT
        value: "10000"
    healthCheckPath: /

  # Background Service for LiveKit Agent
  - type: worker
    name: alex-livekit-agent
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python agent.py"
    plan: free
    envVars:
      - key: LIVEKIT_API_KEY
        value: APITMKfqYVjk79h
      - key: LIVEKIT_API_SECRET
        value: gCkm5chxksS9KKIUrWVDhf7TDVRVeqleZHf49SFPLBMA
      - key: LIVEKIT_URL
        value: wss://sr-fa31r2za.livekit.cloud